# Generated by Django 2.0.2 on 2018-02-27 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mp_rest_api', '0002_auto_20180221_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_rest_api.UserGroup')),
            ],
            options={
                'db_table': 'mp_user_to_user_group',
            },
        ),
    ]
