# Generated by Django 2.0.2 on 2018-02-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_rest_api', '0003_usertousergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertousergroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertousergroup',
            name='user_group',
        ),
        migrations.DeleteModel(
            name='UserToUserGroup',
        ),
    ]
